name: go-convertapitos

services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/migrate"]
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: production
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: ["/app/server" ]

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /data/postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/data/postgres
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge